// <auto-generated />
using System;
using Fundo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoansDbContext))]
    partial class LoansDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundo.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Loans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Loans_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Loans_CurrentBalance_Valid", "[CurrentBalance] >= 0 AND [CurrentBalance] <= [Amount]");

                            t.HasCheckConstraint("CK_Loans_Status_Balance_Consistent", "([Status] = 'Active' AND [CurrentBalance] > 0) OR ([Status] = 'Paid' AND [CurrentBalance] = 0)");

                            t.HasCheckConstraint("CK_Loans_Status_Valid", "[Status] IN ('Active', 'Paid')");

                            t.HasCheckConstraint("CK_Loans_Type_Valid", "[Type] IN ('Personal', 'SmallBusiness', 'Bridge')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Amount = 25000m,
                            ApplicantName = "John Doe",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 18750m,
                            Status = "Active",
                            Type = "Personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Amount = 15000m,
                            ApplicantName = "Jane Smith",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 0m,
                            Status = "Paid",
                            Type = "Personal"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Amount = 50000m,
                            ApplicantName = "Robert Johnson",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 32500m,
                            Status = "Active",
                            Type = "SmallBusiness"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Amount = 10000m,
                            ApplicantName = "Emily Williams",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 0m,
                            Status = "Paid",
                            Type = "Personal"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Amount = 75000m,
                            ApplicantName = "Michael Brown",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentBalance = 72000m,
                            Status = "Active",
                            Type = "Bridge"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
